### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function WPGraphQL\MetaQuery::add_input_fields()

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql-meta-query#8]
I just updated 1.0.0 and now get this error.

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function WPGraphQL\MetaQuery::add_input_fields(), 3 passed in /www/wp-includes/class-wp-hook.php on line 286 and exactly 4 expected in /www/wp-content/plugins/wp-graphql-meta-query/wp-graphql-meta-query.php:139 Stack trace: #0 /www/wp-includes/class-wp-hook.php(286): WPGraphQL\MetaQuery->add_input_fields(Array, 'RootQueryToCate...', Array) #1 /www/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array) #2 /www/wp-content/plugins/wp-graphql/src/Type/WPInputObjectType.php(40): apply_filters('graphql_input_f...', Array, 'RootQueryToCate...', Array) #3 /www/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(440): WPGraphQL\Type\WPInputObjectType::prepare_fields(Array, 'RootQueryToCate...') #4 [internal function]: WPGraphQL\Registry\TypeRegistry->WPGraphQL\Registry\{closure}() #5 /www/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/InputObjectType.php(50): call_user_func(Object(Closure)) #6 /www/wp-content/plugins/wp- in /www/wp-content/plugins/wp-graphql-meta-query/wp-graphql-meta-query.php on line 139 
```

**Comment by jasonbahl** [comment]
This PR should fix this: https://github.com/wp-graphql/wp-graphql/pull/1038

I'll get out another point release here shortly
